services:
  remnanode:
    container_name: remnanode
    hostname: remnanode
    image: remnawave/node:latest
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    env_file:
      - .env
    volumes:
      - /dev/shm:/dev/shm:rw
      - /var/log/remnanode:/var/log/remnanode

  adguard:
    container_name: adguard
    hostname: adguard
    image: adguard/adguardhome:latest
    restart: always
    network_mode: host
    volumes:
      - ./adguard/work:/opt/adguardhome/work:rw
      - ./adguard/conf:/opt/adguardhome/conf:rw
    environment:
      - AGH_CONFIG=/opt/adguardhome/conf/AdGuardHome.yaml

  nginx:
    image: nginx:1.26
    container_name: nginx
    hostname: nginx
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./privkey.key:/etc/nginx/ssl/privkey.key:ro
      - /dev/shm:/dev/shm:rw
    restart: always
    depends_on:
      - adguard 
