global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: remnawave
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["remnawave:3001"]
    basic_auth:
      username: metricsUser
      password: # openssl rand -hex 64

  - job_name: xray-checker
    metrics_path: /metrics
    scrape_interval: 60s
    static_configs:
      - targets: ["xray-checker:2112"]
    basic_auth:
      username: metricsUser
      password: # openssl rand -hex 64
